### ISSUE TITLE
Debugging connectivity issues

### ISSUE THREAD

**Issue by rjpearce** [DrJohnM61/poesp32-esphome#2]
Hi, Thank you for putting this together it is awesome. 

I'm currently having some connectivity issues and I wanted to check a few things with you.

I bought one of these which looks very similar to the one in your photo: https://www.amazon.co.uk/dp/B07BBPX8B8?psc=1&ref=ppx_yo2ov_dt_b_product_details

When I connect the pins correctly PWR, RXD and TXD light-up and RXD and TXD both blink together every second no serial device shows up (looks like a short?). 
If I remove GND I get the PWR light and the serial device shows up. If I then try and access the serial device I can see TXD flash but there is no RXD response. I tried swapping RXD and TXD but without success.

Did you have any issues when you originally tried to get it working?

Thanks
![PXL_20240323_130504745 MP](https://github.com/DrJohnM61/poesp32-esphome/assets/3367673/526afb19-e069-40cb-be5c-741ff72b6694)

**Comment by DrJohnM61** [comment]
The device looks very similar to what I am using.

The RX needs to be connected to TX and TX to RX (it appears correct in the photo you provided).

The G0 pin only needs to be held on the top of the ESP32 when plugging the USB cable of the serial adaptor into the computer and then remove the G0 cable. All that does is to force the ESP32 into boot loader mode (note, you do this without any POE ethernet plugged in). So, to clarify... have the poesp32 unplugged from the ethernet but connected to the serial adaptor. Have the serial adaptor unplugged from the computer. Touch (and hold) the G0 fly lead to the top of the ESP32 (the metal can of the chip). While holding the fly lead to the ESP32, plug in the serial adaptor to the computer (thereby providing power). Remove the G0 fly lead. On a Mac computer, you should see the usbserial device in the /dev directory (from the terminal application, type ls /dev/ | grep cu.usbserial).

The lights on the USB serial dongle will only flash when you are uploading the compiled code.

Do you have the correct voltage strap on the serial adaptor? This (according to the Schematic at https://docs.m5stack.com/en/unit/poesp32 - download socket, bottom right of the diagram) should be 3.3v. You can see the black strap plug on the serial adaptor near the USB plug and that should be connected VCC/3V3

Some other things to try...

The plug that is going into the poesp32 is obviously not soldered, so you do need to put a bit of torsion on the plug (ie, push it sideways) so that it makes full contact with the holes.

I am not at home for the next week, so a little difficult to check anything else. I suspect you are not getting into boot loader mode. Hopefully, the extra information above can help.

**Comment by rjpearce** [comment]
Thank you for the advice I managed to get it working using your tips.

It was certainly rather awkward.

1. Use your thumb to apply side pressure to the plug that goes into the poesp32 to ensure they make contact
2. Use a finger to hold the fly lead on G0
3. Use the rest of your fingers and spare hand to plug in the USB device 
4. Use your spare hand to run the esphome commands

Sharing back I can confirm that UART works with the poesp32 when using esphome. I am using it to stream RS232 over the network.

```yaml
uart:
  id: uart_bus
  baud_rate: 9600
  tx_pin: 17
  rx_pin: 16
  stop_bits: 1
  data_bits: 8
  parity: NONE
  debug:
    direction: BOTH
    dummy_receiver: false

stream_server:
  id: my_stream
  uart_id: uart_bus
  port: 7777
```

I will cross post to this [project](https://github.com/davesmeghead/visonic/wiki/Hardware-Setup) and link back.
